### ISSUE TITLE
Fix the user stories & use cases according to Week 7 Tutorial

### ISSUE THREAD

**Issue by UncleGrandpa925** [AY2021S1-CS2103T-W13-4/tp#25]
Hi @nguyendqminh 

Can you take a look at the current user stories & use cases to see if there is anything to improve/fix according to the Week 7 Tutorial? Add more obvious and essential user stories? 

@simonteozw can you help Minh verify this after he is done?

Thanks

**Comment by nguyendqminh** [comment]
Noted with thanks. I will finish it by tomorrow (Sat) 6pm.
