### ISSUE TITLE
Rename personal images

### ISSUE THREAD

**Issue by UncleGrandpa925** [AY2021S1-CS2103T-W13-4/tp#9]
Hi guys, as stated in this guide:
https://nus-cs2103-ay2021s1.github.io/website/schedule/week7/project.html
You should rename your personal image to "githbub_username_in_lower_case.png" , then create a pull request! @simonteozw will review and merge the pull request

**Comment by justweihong** [comment]
Yes, I realised it too but I forgot to raise it up during yesterday's meeting! Will send Simon another PR.

**Comment by UncleGrandpa925** [comment]
> Yes, I realised it too but I forgot to raise it up during yesterday's meeting! Will send Simon another PR.

Ah I resolved it already! Forgot to close this issue
